apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-tomat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: my-tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - name: my-tomcat
        image: kimclog/mytomcat:0.0
        ports:
        - containerPort: 8080
          protocol: TCP
