apiVersion: v1
kind: Service
metadata:
  name: myregistry-svc
spec:
  ports:
    - name: port
      port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    app: myregistry
  type: NodePort
