apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-simple-hpa
  targetCPUUtilizationPercentage: 50
  maxReplicas: 5
  minReplicas: 1
