apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-toyproject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-main
  targetCPUUtilizationPercentage: 10
  maxReplicas: 5
  minReplicas: 1
