apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db1
  labels:
    db: db1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.141
    path: /nfs/toyproject/db1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db2
  labels:
    db: db2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.141
    path: /nfs/toyproject/db2
