apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db1
spec:
  selector:
    matchLabels:
      db: db1
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db2
spec:
  selector:
    matchLabels:
      db: db2
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
