version: '3.0'
services:
  python:
    build:
      context: /root/dockerfile/python/
      dockerfile: /root/dockerfile/python/Dockerfile
    image: myapp:0.0
    restart: always
  mysql:
    build:
      context: /root/dockerfile/mysql/
      dockerfile: /root/dockerfile/mysql/Dockerfile
    image: mysql:0.0
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    external: true
